#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**************************\
|*  ROBOTC Virtual World  *|
|*  Turning with Encoders *|
\**************************/

// This program makes a sharp turn using the encoders for reproducable accuracy.

task main()
{
  SensorValue[rightEncoder] = 0;          // reset encoder to 0

  while(SensorValue[rightEncoder] < 100)  // while the right encoder value is less than 100:
  {
                                      // turn LEFT in place:
    motor[rightMotor] = 75;           // set port2 to speed 75
    motor[leftMotor]  = -75;          // set port3 to speed 75
  }
                                      // stop the robot:
  motor[rightMotor] = 0;              // set port2 to speed 0
  motor[leftMotor]  = 0;              // set port3 to speed 0
}
