#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**************************\
|*  ROBOTC Virtual World  *|
|*  Forward until Sonar   *|
\**************************/

// This program goes forward until the sonarSensor sensor sees an object closer than our 'threshold'.

task main()
{
  int threshold = 40;   // create and set variable 'threshold' to 40 (will be distance for sonarSensor)

  while(SensorValue(sonarSensor) > threshold || SensorValue(sonarSensor) == -1)   // while the sonarSensor sensor is reading in values larger than our
  {                                                                   // threshold, or reading out of range (-1 = no object in sight)
                              // move forward:
    motor[rightMotor] = 75;   // set port2 to speed 75
    motor[leftMotor]  = 75;   // set port3 to speed 75
  }
                              // stop the robot:
  motor[rightMotor] = 0;      // set port2 to speed 0
  motor[leftMotor]  = 0;      // set port3 to speed 0
}
