#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**************************************\
|*  ROBOTC Virtual World (GAMEBOARD)  *|
|*  Until Touch (Natural Language)    *|
\**************************************/

// This program drives forward at speed 50 until
// the touch sensor is pressed, it then backs up
// at speed 50 and then makes a sharp right turn.

task main()
{
  forward(50);        // drive forward at speed 50
  untilTouch();       // continue until the touch sensor is pressed

  backward(50);       // drive backward at speed 50
  wait(1.5);          // wait 1.5 seconds

  pointTurn(right);   // make a sharp right turn
  wait(0.75);         // wait 0.75 seconds
  stop();             // stop the robot
}
