#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**************************************\
|*  ROBOTC Virtual World (GAMEBOARD)  *|
|*  Until Dark (Natural Language)     *|
\**************************************/

// This program drives forward at speed 50 until
// the light sensor sees a dark line and then stops.
// 0 is darkest, 4095 = lightest

task main()
{
  forward(50);    // drive forward at speed 50
  untilDark();    // continue until the light sensor reads a dark line
  stop();         // stop
}
