#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/******************************************************\
|*  ROBOTC Virtual World (GAMEBOARD)                  *|
|*  Gripper Challenge with Timing (Natural Language)  *|
\******************************************************/

// This program drives forward for 5.2 seconds, grabs
// the blue robot, and then reverses for 5.2 seconds.

task main()
{
  startMotor(gripperMotor, -100);	// open gripperMotor at speed -100
  wait(1.0);                  		// wait 1.0 seconds
  stopMotor(gripperMotor);         	// stop gripperMotor

  forward(50);                		// drive forward at speed 50
  wait(6.0);                  		// wait for 6.0 seconds
  stop();                    		// stop

  startMotor(gripperMotor, 100);  	// close gripperMotor at speed 100
  wait(1.0);                  		// wait 1.0 seconds
  stopMotor(gripperMotor);         	// stop gripperMotor

  backward(50);               		// drive backward at speed 50
  wait(5.2);                  		// wait 5.2 seconds
  stop();                     		// stop
}
