#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**************************************\
|*  ROBOTC Virtual World (GAMEBOARD)  *|
|*  Smooth Sonar Detection            *|
\**************************************/

// This program uses the sonarSensor sensor to approach and object and maintain a set
// distance from it.  (if the object moves closer, the robot will back up)

task main()
{
  int speed = 0;          // will hold the speed of the motors
  int sonarValue = 0;     // will hold the values read in by the Sonar Sensor
  int distance = 12;      // specified distance to be at 12 centimeters

  while(true)
  {
    sonarValue = SensorValue(sonarSensor);        // set 'sonarValue' to the current reading of the sonarSensor sensor

    if(sonarValue == -1)                    // if the object is out of range:
    {
      speed = 100;                          // set speed to 100
    }
    else                                    // otherwise, if we see and object:
    {
      speed = (sonarValue - distance) * 5;  // set 'speed' to the (sonarSensor reading - our desired distance) * 5 for speed
    }

    motor[rightMotor] = speed;              // set motorB is run at a power level equal to 'speed'
    motor[leftMotor]  = speed;              // set motorC is run at a power level equal to 'speed'
  }
}
