#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**************************************\
|*  ROBOTC Virtual World (GAMEBOARD)  *|
|*  Line Following for Time           *|
\**************************************/

// This program follows a black line on a white surface for 3500 milliseconds.
// 0 is darkest, 4095 = lightest

task main()
{
  int threshold = 2048;           // Create a threshold variable to differentiate between light and dark.
  int time = 3500;                // Create a time variable for how many seconds we want to follow the line.

  ClearTimer(T1);                 // Clear timer, 'T1' for use.

  while(time1[T1] < time)         // While T1 is less than 'time':
  {
    if(SensorValue(lightSensor) < threshold) // If the sensor sees a value less than our threshold (dark):
    {
      // turn right:
      motor[rightMotor] = 5;
      motor[leftMotor]  = 55;
    }
    else                                      // If the sensor sees a value greater than our threshold (light):
    {
      // turn left:
      motor[rightMotor] = 55;
      motor[leftMotor]  = 5;
    }
  }
}
