#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**************************************\
|*  ROBOTC Virtual World (GAMEBOARD)  *|
|*  Avoiding obstacles with the Sonar *|
\**************************************/

// This program drives forward until the sonarSensor sensor sees an object closer than a
// set 'threshold' variable.  It then backs up and turns right until it sees some space.

int threshold = 12;   // threshold for sonarSensor sensor


task main()
{
  // run forever:
  while(true)
  {
    // go forward at speed 75:
    motor[rightMotor] = 75;
    motor[leftMotor]  = 75;

    // if an object is detected closer than our 'threshold':
    if(SensorValue(sonarSensor) < threshold && SensorValue(sonarSensor) != -1)
    {
      // HALT and back up!:
      motor[rightMotor] = -75;
      motor[leftMotor]  = -75;
      wait1Msec(1000);

      // turn until the path ahead seems clear:
      while(SensorValue(sonarSensor) < (threshold * 2))
      {
        // turn right in place at speed 75:
        motor[rightMotor] = -75;
        motor[leftMotor]  = 75;
      }
    }
  }
}
