#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**************************************\
|*  ROBOTC Virtual World (GAMEBOARD)  *|
|*  Line Following for Distance       *|
\**************************************/

// This program follows a black line on a white surface for 1260 encoder counts.
// 0 is darkest, 4095 = lightest

task main()
{
  int threshold = 2048;           // Create a threshold variable to differentiate between light and dark.
  int distance = 1260;            // Create a distance variable for how many encoder counts we want to follow the line.

  SensorValue(rightEncoder) = 0;  // Reset the right motor encoder to 0.

  while(SensorValue(rightEncoder) < distance) // While the right motor encoder is less than 'distance':
  {
    if(SensorValue(lightSensor) < threshold) // If the sensor sees a value less than our threshold (dark):
    {
      // turn right:
      motor[rightMotor] = 5;
      motor[leftMotor]  = 55;
    }
    else                                      // If the sensor sees a value greater than our threshold (light):
    {
      // turn left:
      motor[rightMotor] = 55;
      motor[leftMotor]  = 5;
    }
  }
}
