#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**********************************************\
|*  ROBOTC Virtual World (GAMEBOARD)          *|
|*  Avoiding obstacles with the Touch sensor  *|
\**********************************************/

// This program drives backward until the touchSensor sensor is pressed.
// It then goes forward and turns right before continuing backward.


task main()
{
  // run forever:
  while(true)
  {
    // go backward at speed -75:
    motor[rightMotor] = -75;
    motor[leftMotor]  = -75;

    // if the touchSensor sensor is pressed:
    if(SensorValue(touchSensor) == 1)
    {
      // HALT and move forward!:
      motor[rightMotor] = 75;
      motor[leftMotor]  = 75;
      wait1Msec(1000);

      // turn right in place at speed 75:
      motor[rightMotor] = -75;
      motor[leftMotor]  = 75;
      wait1Msec(1000);
    }
  }
}
