#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**************************\
|*  ROBOTC Virtual World  *|
|*  Forward until Dark    *|
\**************************/

// This program drives forward until the light sensor reads
// a value greater than the threshold and then stops.
// 0 is darkest, 4095 = lightest


task main()
{
  int threshold = 2700;   // create a threshold to differentiate between light and dark

  // while the line follower reads a value darker than our threshold:
  while(SensorValue[lightSensor] < threshold)
  {
    // go forward at speed 75
    motor[rightMotor] = 75;
    motor[leftMotor]  = 75;
  }
}
