#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/********************************\
|*  ROBOTC Virtual World        *|
|*  encoders (Natural Language) *|
\********************************/

// This program drives forward for 2.0 rotations of the encoder, and then
// backward for 720 counts of the encoder.  (360 counts = 1.0 encoder)

task main()
{
  forward(75);                       		// move forward at speed 75
  untilRotations(2.0, leftEncoder);  		// continue until the left encoder reads 2.0 rotations (720 counts)
  stop();                            		// stop the robot

  wait(1.0);                         		// wait for 1 second

  backward(75);                      		// move backward at speed 75
  untilEncoderCounts(720, leftEncoder);		// continue until the left encoder reads 720 counts (2.0 rotations)
  stop();                            		// stop the robot
}
