#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/****************************************************\
|*  ROBOTC Virtual World                            *|
|*  Move Straight for Rotations (Natural Language)  *|
\****************************************************/

// This program makes small corrections based on the values
// of the encoders to drive in a straight line for 5.0 rotations.

task main()
{
  moveStraightForRotations(5.0);    // drive straight forward for 5.0 rotations
  stop();                           // stop the robot
}
