#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/**********************************\
|*  ROBOTC Virtual World          *|
|*  Swing Turn (Natural Language) *|
\**********************************/

// This program makes a wide turn left for 1.5 seconds
// Followed by a wide turn right for 1.5 seconds.

task main()
{
  swingTurn(left);    // make a wide left turn
  wait(1.5);          // wait for 1.5 seconds
  stop();             // stop

  wait(1.0);          // wait for 1.0 seconds

  swingTurn(right);   // make a wind right turn
  wait(1.5);          // wait for 1.5 seconds
  stop();             // stop
}
