#pragma config(ProgramType, StandaloneUSBCable)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  //nCortexCommType = ctUSBCable;
  while (true)
  {
    motor[port8] = -40;
    motor[port9] = -40;
    motor[port1] = -40;
    motor[port10] = -40;

    wait1Msec(500);

    motor[port8] = 40;
    motor[port9] = 40;
    motor[port1] = 40;
    motor[port10] = 40;

    wait1Msec(500);

    motor[port8] = 0;
    motor[port9] = 0;
    motor[port1] = 0;
    motor[port10] = 0;

    wait1Msec(500);
  }
}
